is212g7t5/spm

- app/netlify.toml
Add netlify config file to ignore changes in non-FE folders
> Add netlify config to only build on FE change

- backend/alembic/versions/0002_create_skills.py
- backend/app/models/skill.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Fix failing Skill table

- app/package-lock.json
- app/package.json
- app/src/App.jsx
- app/src/App.test.jsx
- app/src/components/course/CourseDesc.jsx
- app/src/components/course/CourseDescription.jsx
- app/src/components/course/CourseTile.jsx
- app/src/components/course/index.jsx
- app/src/routes/courses/index.jsx
* Created Course View and Route
* Downgraded Router from 6 to 5
https://user-images.githubusercontent.com/74455943/191666229-dde843bf-ec22-4f0c-a0bf-0e70f5b8e378.mov
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> [G7T5-53] Create View for Courses

- app/src/App.jsx
- app/src/components/course/CourseStatusBadge.jsx
- app/src/components/course/CourseTile.jsx
- app/src/components/course/index.jsx
Fixes [G7T5-89](https://is212g7t5.atlassian.net/browse/G7T5-89)
> [G7T5-89] Updated Course Status with Registration and Completion status

- backend/app/api/api_v1/api.py
- backend/app/api/api_v1/endpoints/job.py
- backend/app/main.py
- backend/app/tests/api/api_v1/test_job.py
- backend/app/tests/utils/job_skill.py
- Add getAllJobAllSkill API with an SQL query
- Add unfinished Test case to test happy path for above API
- No ticket
> [No Ticket] Add getAllJobAllSkill API and happy path test

- backend/app/models/skill_course.py
Fixes [Jira ticket G7T5-94](https://is212g7t5.atlassian.net/browse/G7T5-94)
> Fix course_id's type in model

- app/src/App.jsx
- app/src/components/Navbar.jsx
- app/src/components/course/index.jsx
- app/src/components/course/staff/StaffCourse.jsx
- app/src/components/user/Login.jsx
- app/src/components/user/UserContext.jsx
- app/src/components/user/UserNavigation.jsx
Add role switching capability and role state on frontend to allow access control via roles
Fixes [Jira ticket G7T5-62](https://is212g7t5.atlassian.net/browse/G7T5-62)
**Default**
**Using Staff to view the Staff's view of course**
**Using HR, cannot view the Staff's view**
> [G7T5-62] Add sessionstorage and context user

- app/src/components/job/JobTile.jsx
- app/src/components/job/hr/HRJob.jsx
- app/src/components/job/index.jsx
- app/src/components/job/staff/StaffJob.jsx
- app/src/contexts/UserContext.jsx
Added HR Job Page, with routing configured to be access controlled as a "HR" user. This involves migration of previous Job Page logic to Staff-specific Job Page in order to support the same route but different render depending on the user role.
Fixes [Jira ticket #G7T5-79](https://is212g7t5.atlassian.net/browse/G7T5-79) and [Jira ticket #G7T5-96](https://is212g7t5.atlassian.net/browse/G7T5-96)
- Added differentiation of active and inactive job roles for HR's Job Page
- As a byproduct, Staff can now view inactive jobs. This should be rectified.
- Added background color to Job description section for visibility
> [G7T5-79, G7T5-96] Add HR Job Page with Access Control

- app/src/components/job/hr/HRJob.jsx
- app/src/routes/jobs/index.jsx
Fixes [Jira ticket #G7T5-78](https://is212g7t5.atlassian.net/browse/G7T5-78)
Add a button for HR to "Create new job". Currently, it routes to the same page. This will be rerouted when the create new job page functionality is available.
No testcases
> Add create new job button for HR

- app/src/layout/Login.jsx
- app/src/layout/Navbar.jsx
- app/tailwind.config.js
Fixes [Jira ticket G7T5-99](https://is212g7t5.atlassian.net/browse/G7T5-99)
> [G7T5-99] Created Colour Scheme

- app/src/api/jobs.js
- app/src/api/learningJourney.js
- app/src/components/learningJourney/LearningJourneyTile.jsx
- app/src/components/learningJourney/index.jsx
- app/src/components/learningJourney/staff/StaffLearningJourney.jsx
- app/src/contexts/UserContext.jsx
Fixes [Jira ticket G7T5-91](https://is212g7t5.atlassian.net/jira/software/c/projects/G7T5/boards/4?modal=detail&selectedIssue=G7T5-91)
* Note: UserId has been mocked in the context
> [G7T5-91] Retrieved Job details from Learning Journeys 

- app/src/components/job/JobTile.jsx
Fixes [Jira ticket #G7T5-82](https://is212g7t5.atlassian.net/browse/G7T5-82)
Adds edit job button. Currently, the button does not have any action associated. This will be resolved in https://is212g7t5.atlassian.net/browse/G7T5-83
> [G7T5-82] Add edit job button for HR

- app/src/App.jsx
- app/src/api/jobs.js
- app/src/components/job/JobTile.jsx
- app/src/components/job/hr/CreateJob.jsx
- app/src/components/job/hr/UpdateJob.jsx
- app/src/components/job/hr/UpdateJobSuccess.jsx
- app/src/contexts/UpdateJobContext.jsx
- app/src/routes/index.jsx
- app/src/routes/updateJob/index.jsx
Fixes [Jira ticket #G7T5-83](https://is212g7t5.atlassian.net/browse/G7T5-83) and [Jira ticket #G7T5-84](https://is212g7t5.atlassian.net/browse/G7T5-84)
Adds `/update-job` page that relies on global context to preload the respective fields. All fields will then be piped to the PUT `/jobs` endpoint.
> [G7T5-83, G7T5-84] Create update job page for HR

- app/.env-example
- app/src/api/learningJourneyCourse.js
- app/src/components/createLearningJourney/CourseModal.jsx
- app/src/components/createLearningJourney/CoursesList.jsx
- app/src/components/createLearningJourney/JobSkills.jsx
- app/src/components/createLearningJourney/index.jsx
- app/src/components/job/hr/CreateJobSuccess.jsx
- app/src/components/skill/SkillTile.jsx
- app/src/contexts/LJCreationContext.jsx
- app/src/layout/Login.jsx
- app/src/layout/Navbar.jsx
- app/src/utils/mocks.js
- app/tailwind.config.js
https://is212g7t5.atlassian.net/browse/G7T5-11
- Add Global Context to store some user needed states
- FE now can add or remove components
- Error handling for components removal or addition
Create LJ
Selecting a course
Course Appears
Course can also be deleted
> [G7T5-76] Add Courses to LJ

- app/src/api/skills.js
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/index.jsx
Fixes [Jira ticket 41](https://is212g7t5.atlassian.net/browse/G7T5-41?atlOrigin=eyJpIjoiZDA4NTBmNTU1YzQ3NGIxOWIyOTIyZjJmNGRlMzczYjciLCJwIjoiaiJ9)
> [G7T5-41]Display active courses only

- app/src/api/jobs.js
- app/src/components/learningJourney/staff/StaffLearningJourney.jsx
- app/src/contexts/UserContext.jsx
Fixes [Jira ticket G7T5-120](https://is212g7t5.atlassian.net/browse/G7T5-120)
> [G7T5-120] Fix bug where LJ was not displaying

- app/src/api/skills.js
- app/src/components/job/staff/StaffJob.jsx
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/index.jsx
- app/src/components/skill/staff/StaffSkill.jsx
- backend/app/api/api_v1/endpoints/skill.py
- backend/app/crud/base.py
- backend/app/crud/crud_skill.py
- backend/app/tests/api/api_v1/test_skill.py
- backend/app/tests/utils/skill.py
- backend/app/tests/utils/skill_course.py
Fixes https://is212g7t5.atlassian.net/browse/G7T5-122
- Created BE APIs for Get Active Skills, Get Active Skills And Courses. Minor change to path for current Get All Skills API
- Call Get Active Skills And Courses API for new StaffSkill component
> [G7T5-122] Close access to inactive Skills for non-HR

- app/src/components/job/index.jsx
Fixes [Jira ticket G7T5-110](https://is212g7t5.atlassian.net/jira/software/c/projects/G7T5/boards/4?modal=detail&selectedIssue=G7T5-110)
Fixes [Jira ticket G7T5-111](https://is212g7t5.atlassian.net/jira/software/c/projects/G7T5/boards/4?modal=detail&selectedIssue=G7T5-111)
> [G7T5-127] [G7T5-128] Reused Staff Job component for Manager

- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/hr/HRSkill.jsx
- app/src/components/skill/index.jsx
- app/src/utils/mocks.js
Fixes https://is212g7t5.atlassian.net/browse/G7T5-133
> [G7T5-133] FE for HR View All Skills

- app/src/components/skill/hr/HRSkill.jsx
- app/src/components/skill/staff/StaffSkill.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-134
> [G7T5-134] Call BE API to get all skills for HRSkill

- app/src/api/learningJourney.js
- app/src/api/learningJourneyCourse.js
- app/src/components/createLearningJourney/SubmitButton.jsx
- app/src/components/createLearningJourney/index.jsx
- app/src/contexts/UserContext.jsx
- app/src/layout/Login.jsx
- app/src/layout/UserNavigation.jsx
Fixes [Jira ticket G7T5-92](https://is212g7t5.atlassian.net/jira/software/c/projects/G7T5/boards/4?selectedIssue=G7T5-114)
* Finish flow to create learning journey
* Setup `staffId` in UserContext
* Disabled submit button if no courses selected
https://user-images.githubusercontent.com/74455943/195599614-b6abdd5c-03c0-4ad0-b996-77d7e1fab82f.mov
> [G7T5-92] Create Submit Button for 'Create Learning Journey' and included staffId in UserContext

- app/src/components/skill/hr/HRSkill.jsx
- app/src/components/skill/staff/StaffSkill.jsx
- app/src/routes/skills/index.jsx
Fixes [Jira ticket #G7T5-129](https://is212g7t5.atlassian.net/browse/G7T5-129)
Adds button to create skill for HR. Currently the button routes back to the `/skills` page since the create skill functionality is not created yet.
Also made visual changes to standardise `/jobs` and `/skills`
NA, will add appropriate test cases in subsequent ticket for create skill functionality.
> [G7T5-129] Add create skill button for HR

- app/src/components/job/JobTile.jsx
- app/src/components/skill/SkillTile.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-104
Dummy button, pure FE only.
> [G7T5-104] Edit Skill button for HR

- app/src/api/learningJourneyCourse.js
- app/src/components/createLearningJourney/index.jsx
- app/src/contexts/UserContext.jsx
* LJ and Course Mapping hot fix
> [Bugfix] Fixed Error when writing new LJ and Course mappings

- app/src/api/learningJourney.js
- app/src/components/learningJourney/DropdownButton.jsx
- app/src/components/learningJourney/LearningJourneyTile.jsx
- app/src/components/learningJourney/details/LJDeletionPopUp.jsx
- app/src/components/learningJourney/staff/StaffLearningJourney.jsx
Fixes [Jira ticket G7T5-121](https://is212g7t5.atlassian.net/browse/G7T5-121)
> [G7T5-121] Fix LJ Deletion Popup

- app/src/App.jsx
- app/src/components/learningJourney/DropdownButton.jsx
- app/src/components/learningJourney/LearningJourneyTile.jsx
- app/src/components/learningJourney/details/index.jsx
- app/src/layout/Navbar.jsx
- app/src/routes/learningJourneys/index.jsx
https://is212g7t5.atlassian.net/browse/G7T5-139
You can now access the LJ details page through URL or through the edit button
No TC as this is a subtask.
TC will be added for the main Usersotry PR
> [G7T5-139] Link FE LJ Details via query params

- app/src/api/skills.js
- app/src/components/job/hr/CreateJob.jsx
- app/src/components/skill/hr/CreateSkill.jsx
- app/src/components/skill/hr/CreateSkillSuccess.jsx
- app/src/components/skill/hr/HRSkill.jsx
Fixes [Jira ticket #G7T5-131](https://is212g7t5.atlassian.net/browse/G7T5-131)
**Create Skill Success**
**Create Skill Error**
> [G7T5-131] Trigger backend request to create skill

- app/src/components/createLearningJourney/CoursesList.jsx
- app/src/components/createLearningJourney/DeleteSkillModal.jsx
- app/src/components/createLearningJourney/index.jsx
Fixes [Jira ticket G7T5-72](https://is212g7t5.atlassian.net/browse/G7T5-72)
https://user-images.githubusercontent.com/89028059/196177733-69a01e64-de9b-4b1f-9a20-f47b9e4b5fd3.mov
> [G7T5-72] Create FE Components when Staff deletes courses in new LJ

- app/src/components/skill/hr/CreateSkill.jsx
- app/src/layout/Login.jsx
Fixes [Jira ticket #G7T5-132](https://is212g7t5.atlassian.net/browse/G7T5-132)
Allow only HR users to access the `/create-skill`, and do not render the page for other user types
**Logged in as HR:**
**Not logged in as HR**
Additional bug fix where role selection menu was hidden behind tiles
> [G7T5-132] Add access control to create-skill page

- app/src/api/skills.js
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/hr/DeactivateSkillModal.jsx
- app/src/components/skill/hr/HRSkill.jsx
- app/src/components/skill/hr/StopDeactivateSkillModal.jsx
Fixes [Jira ticket G7T5-136](https://is212g7t5.atlassian.net/browse/G7T5-136) and [Jira ticket G7T5-137](https://is212g7t5.atlassian.net/browse/G7T5-137)
https://user-images.githubusercontent.com/89028059/196848476-349af6b7-2e01-447c-a6e9-7ddd525f4c8f.mov
> [G7T5-136 & G7T5-137] Create HR Soft-Delete Skills

- app/src/App.jsx
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/hr/UpdateSkill.jsx
- app/src/components/skill/hr/UpdateSkillSuccess.jsx
- app/src/components/skill/hr/form/SkillIsActiveToggle.jsx
- app/src/contexts/UpdateSkillContext.jsx
- app/src/routes/index.jsx
- app/src/routes/updateSkill/index.jsx
Fixes:
https://is212g7t5.atlassian.net/browse/G7T5-142
https://is212g7t5.atlassian.net/browse/G7T5-144
https://user-images.githubusercontent.com/71003267/196875350-15539673-1c47-48c4-acfe-35be9effed3a.mp4
> [G7T5-142, G7T5-144] Create and link FE for UpdateSkill page

- app/src/components/course/CourseStatusBadge.jsx
- app/src/components/course/CourseTile.jsx
- app/src/components/course/staff/StaffCourse.jsx
Fixes [Jira ticket #49](https://is212g7t5.atlassian.net/browse/G7T5-49?atlOrigin=eyJpIjoiMWViNzg2ZDljNWEwNGVhZGE4NDJlMjhmMGVjOWUzNjMiLCJwIjoiaiJ9)
Display Course status in Courses page when logged in as "Staff"
> [G7T5-49] Calling API to View Course Status

- app/src/api/skills.js
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/hr/DeactivateSkillModal.jsx
- app/src/components/skill/hr/UpdateSkill.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-143
https://user-images.githubusercontent.com/71003267/197119388-9d250252-c99b-4ec3-b099-f5992e5f2b5b.mp4
> [G7T5-143] Call BE API to update skill for HR

- app/src/components/skill/index.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-148
> [G7T5-148] Route Manager Skills page to Staff's Skills page

- app/src/api/learningJourney.js
- app/src/api/learningJourneyCourse.js
- app/src/components/createLearningJourney/SubmitButton.jsx
- app/src/components/createLearningJourney/index.jsx
- app/src/components/learningJourney/DropdownButton.jsx
- app/src/components/learningJourney/details/CourseContainer.jsx
- app/src/components/learningJourney/details/index.jsx
https://is212g7t5.atlassian.net/browse/G7T5-88
User can now update and existing LJ
- Edit LJ CU submitButton to make it reusable
- Edit FE API fns to handle err + formatted them
- Edit CreateLJ page to be compatible with Update
- Removed unnecessary console logs 
[create LJ page is now reusable]
[LJ updated]
[LJ after update]
Please indicate the test case ID you have added or are using
> [G7T5-88] Staff Update existing LJ

- app/src/components/learningJourney/DropdownButton.jsx
- app/src/components/learningJourney/LearningJourneyTile.jsx
- app/src/components/learningJourney/details/LJDeletionPopUp.jsx
- app/src/components/learningJourney/staff/StaffLearningJourney.jsx
Fixes [Jira ticket #]()
https://user-images.githubusercontent.com/89028059/197411985-43f22be2-67ac-46c5-9d24-bdb46185d5ed.mov
> [G7T5-150] Fix LJ Refreshing due to LJ Deletion

- app/src/layout/Navbar.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-99
(wasnt running my backend, hence the lack of data displayed)
https://user-images.githubusercontent.com/71003267/198831456-496ed238-244b-49bc-bde2-18e258d34155.mp4
> [G7T5-99] Fix Navbar bug where clicking on tabs does not register

- app/.env-example
- app/README.md
Fixes [Jira ticket #G7T5-175](https://is212g7t5.atlassian.net/browse/G7T5-175)
- Update frontend README to accurately reflect installation and deployment
- Remove default localhost from `.env.example`
- No application logic changes
> [G7T5-175] Update frontend README

- README.md
Fixes [Jira ticket #G7T5-177](https://is212g7t5.atlassian.net/browse/G7T5-177)
- Update overall README to accurately reflect repository description and deployed links
- No application logic changes
> [G7T5-177] Update overall README

- app/src/components/createLearningJourney/CourseModal.jsx
Fixes [Jira ticket #G7T5-152](https://is212g7t5.atlassian.net/browse/G7T5-152)
> [G7T5-152] Add course category in course selection

- backend/app/api/api_v1/endpoints/course.py
- backend/app/tests/api/api_v1/test_course.py
- backend/app/tests/utils/course.py
- backend/app/tests/utils/skill_course.py
Fixes [Jira ticket G7T5-192](https://is212g7t5.atlassian.net/browse/G7T5-192)
> [G7T5-192] Create Endpoint for All Courses with Active Skills

- app/src/components/createLearningJourney/CourseModal.jsx
- app/src/layout/Login.jsx
https://is212g7t5.atlassian.net/browse/G7T5-170
Login Button is no longer visible for modals.
NA
> [G7T5-170] Lower Z-index of login button

- app/src/components/job/JobTile.jsx
- app/src/components/skill/SkillTile.jsx
Fixes [Jira ticket #G7T5-158](https://is212g7t5.atlassian.net/browse/G7T5-158)
Truncate text in job description if it overflows out of the container. Does not affect multi-line strings with spaces.
> [G7T5-158] Truncate Job Description

- app/src/components/SearchBar.jsx
- app/src/components/createLearningJourney/CourseModal.jsx
- app/src/components/createLearningJourney/CoursesList.jsx
- app/src/components/createLearningJourney/SubmitButton.jsx
- app/src/components/job/JobTile.jsx
- app/src/components/job/SkillBadge.jsx
- app/src/components/job/hr/CreateJob.jsx
- app/src/components/job/hr/CreateJobSuccess.jsx
- app/src/components/job/hr/HRJob.jsx
- app/src/components/job/hr/JobDeletionPopUp.jsx
- app/src/components/job/hr/UpdateJob.jsx
- app/src/components/job/hr/UpdateJobSuccess.jsx
- app/src/components/job/hr/form/JobDescTextArea.jsx
- app/src/components/job/hr/form/JobIsActiveToggle.jsx
- app/src/components/job/hr/form/JobNameInput.jsx
- app/src/components/job/staff/StaffJob.jsx
- app/src/layout/Login.jsx
- app/src/layout/Navbar.jsx
- app/tailwind.config.js
Fixes [Jira ticket G7T5-179](https://is212g7t5.atlassian.net/browse/G7T5-179?atlOrigin=eyJpIjoiMjdmNjRjMTE2OTI0NDdiMGJlYTI0OGQxYzUzZmZiMTAiLCJwIjoiaiJ9)
Fixes [Jira ticket G7T5-180](https://is212g7t5.atlassian.net/browse/G7T5-180?atlOrigin=eyJpIjoiNjU4YTk2ZmFiNzQ2NDI1NjlmYTNmNzljYTExOTU1MzUiLCJwIjoiaiJ9)
* Added new tailwind classes
* Updated button hover color transition from accent2 --> accent3
* Updated focus ring color
* Included backdrop-blur during popup
> [G7T5-179] [G7T5-180] Standardised Tailwind classes used in Job Role and LJ flows

- app/src/api/course.js
- app/src/components/course/CourseDescription.jsx
- app/src/components/course/CourseTile.jsx
- app/src/components/course/RegistrationStatusBadge.jsx
- app/src/components/course/hr/HRCourse.jsx
- app/src/components/course/index.jsx
- app/src/components/course/staff/StaffCourse.jsx
- app/src/routes/courses/index.jsx
Fixes [Jira ticket G7T5-193](https://is212g7t5.atlassian.net/browse/G7T5-193)
https://user-images.githubusercontent.com/89028059/199263576-f4de57d7-4435-4d3d-b063-148f1ace4434.mov
> [G7T5-193] Frontend Components for HR view Courses

- app/src/components/createLearningJourney/CoursesList.jsx
Fixes https://is212g7t5.atlassian.net/browse/G7T5-169
> [G7T5-169] Handle overflow for course description for course card in create LJ flow

- app/src/components/createLearningJourney/CourseModal.jsx
- app/src/components/createLearningJourney/CoursesList.jsx
- app/src/components/createLearningJourney/JobSkills.jsx
- app/src/components/createLearningJourney/index.jsx
https://is212g7t5.atlassian.net/browse/G7T5-156
https://is212g7t5.atlassian.net/browse/G7T5-157
https://is212g7t5.atlassian.net/browse/G7T5-165
While creating or editing an LJ, Staff now:
1. Cannot view and select non-active skills
2. Cannot view and select non-active courses
Only shows the active skills
----------------------------
> [G7T5-156, G7T5-157, G7T5-165] Staff cannot view and select inactive courses or skills

- app/src/components/course/hr/HRCourse.jsx
- app/src/components/createLearningJourney/CourseModal.jsx
- app/src/components/createLearningJourney/CoursesList.jsx
- app/src/components/createLearningJourney/DeleteSkillModal.jsx
- app/src/components/createLearningJourney/SubmitButton.jsx
- app/src/components/createLearningJourney/index.jsx
- app/src/components/job/hr/HRJob.jsx
- app/src/components/job/hr/JobDeletionPopUp.jsx
- app/src/components/job/hr/UpdateJob.jsx
- app/src/components/job/hr/form/JobIsActiveToggle.jsx
- app/src/components/job/staff/StaffJob.jsx
- app/src/components/learningJourney/LearningJourneyTile.jsx
- app/src/components/learningJourney/details/AddCourseButton.jsx
- app/src/components/learningJourney/details/LJDeletionPopUp.jsx
- app/src/components/learningJourney/staff/StaffLearningJourney.jsx
- app/src/components/skill/CourseBadge.jsx
- app/src/components/skill/SkillTile.jsx
- app/src/components/skill/hr/CreateSkill.jsx
- app/src/components/skill/hr/CreateSkillSuccess.jsx
- app/src/components/skill/hr/DeactivateSkillModal.jsx
- app/src/components/skill/hr/HRSkill.jsx
- app/src/components/skill/hr/StopDeactivateSkillModal.jsx
- app/src/components/skill/hr/UpdateSkill.jsx
- app/src/components/skill/hr/UpdateSkillSuccess.jsx
- app/src/components/skill/hr/form/SkillDescTextArea.jsx
- app/src/components/skill/hr/form/SkillIsActiveToggle.jsx
- app/src/components/skill/hr/form/SkillNameInput.jsx
- app/src/components/skill/staff/StaffSkill.jsx
Fixes [Jira ticket G7T5-181](https://is212g7t5.atlassian.net/browse/G7T5-181?atlOrigin=eyJpIjoiNmM3NTc2MzgwZDJhNDg3NDgwYTgwYmMyMzZlNjk1ZWQiLCJwIjoiaiJ9)
https://user-images.githubusercontent.com/74455943/199553781-f9e6f7e2-b13d-4e0f-b85a-d129f3e7bf9f.mov
https://user-images.githubusercontent.com/74455943/199553797-08614cd2-6bc8-46cd-a873-994021e9ea23.mov
https://user-images.githubusercontent.com/74455943/199553828-6ce968ce-4d5c-4c80-9cb5-d1936af48828.mov
> [G7T5-181] Standardised Tailwind classes in Skills flow

- app/src/components/job/JobTile.jsx
- app/src/components/skill/SkillTile.jsx
Fixes [Jira ticket G7T5-185](https://is212g7t5.atlassian.net/browse/G7T5-185?atlOrigin=eyJpIjoiZjFhMWI5NDRkZTkwNGYzYTk1MThiOGFhMWRiNDA2NmYiLCJwIjoiaiJ9)
Fixes [Jira ticket G7T5-186](https://is212g7t5.atlassian.net/browse/G7T5-186?atlOrigin=eyJpIjoiZTQzMTJlNTA1MjAzNDJlMTlmN2Q3NGQ5OWFmM2NlM2EiLCJwIjoiaiJ9)
* Standardised HR soft delete Job Role and Skill Flow
https://user-images.githubusercontent.com/74455943/199713402-6b684719-618d-4ecd-941b-7de55254cee6.mov
https://user-images.githubusercontent.com/74455943/199713420-574cbed8-0e8c-4272-a253-c833ce15a507.mov
> [G7T5-185] [G7T5-186] Standardised Soft Delete Job Role and Skill Flow

- backend/app/api/api_v1/endpoints/job_skill.py
- backend/app/crud/crud_job_skill.py
- backend/app/tests/api/api_v1/test_job_skill.py
- backend/app/tests/crud/test_job_skill.py
Fixes [Jira ticket G7T5-196](https://is212g7t5.atlassian.net/browse/G7T5-196)
> [G7T5-196] Create Endpoint to Delete All Skills of A Job

- app/src/components/job/JobTile.jsx
- app/src/components/job/index.jsx
- app/src/components/skill/index.jsx
- app/src/layout/Navbar.jsx
Fixes [Jira ticket #G7T5-163](https://is212g7t5.atlassian.net/browse/G7T5-163)
<details>
<summary><b>STAFF Views</b></summary>
<br>
</details>
<details>
<summary><b>HR Views</b></summary>
<br>
</details>
<details>
<summary><b>MANAGER Views</b></summary>
<br>
</details>
> [G7T5-163] Remove inherited staff permissions on views

- app/src/api/skills.js
- app/src/components/skill/hr/CreateSkill.jsx
- app/src/components/skill/hr/UpdateSkill.jsx
Fixes [Jira ticket G7T5-164](https://is212g7t5.atlassian.net/browse/G7T5-164)
> [G7T5-154 & G7T5-164] Fix Error Message Handling for Existing Skill Name when Creating and Updating Skill

- app/src/api/jobSkill.js
- app/src/components/course/CourseDescription.jsx
- app/src/components/course/SkillBadge.jsx
- app/src/components/job/JobTile.jsx
- app/src/components/job/SkillBadge.jsx
- app/src/components/job/hr/CreateJob.jsx
- app/src/components/job/hr/CreateJobSuccess.jsx
- app/src/components/job/hr/UpdateJob.jsx
- app/src/components/job/hr/UpdateJobSuccess.jsx
- app/src/components/job/hr/form/JobDescTextArea.jsx
- app/src/components/job/hr/form/JobIsActiveToggle.jsx
- app/src/components/job/hr/form/JobNameInput.jsx
- app/src/components/job/hr/form/JobSkillSelection.jsx
- app/src/components/skill/CourseBadge.jsx
- app/src/components/skill/SkillTile.jsx
Fixes [Jira ticket G7T5-9](https://is212g7t5.atlassian.net/browse/G7T5-9) and [Jira ticket G7T5-197](https://is212g7t5.atlassian.net/browse/G7T5-197)
https://user-images.githubusercontent.com/89028059/200041428-a790a764-3986-4bc7-b468-316c25cd5e94.mov
**Jira ticket G7T5-9**
**Jira ticket G7T5-197**
**G7T5-9**
**G7T5-197**
> [G7T5-9 & G7T5-197] HR Add and Remove Skills from Job Role
